spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/todoflow
spring.datasource.username=todoflow
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
jwt.secret-key=${JWT_SECRET_KEY}