CREATE TABLE todos (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       title VARCHAR(150) NOT NULL,
                       description TEXT,

                       completed BOOLEAN NOT NULL DEFAULT FALSE,

                       owner_id BIGINT NOT NULL,

                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT fk_todos_owner
                           FOREIGN KEY (owner_id)
                               REFERENCES users(id)
);