CREATE TABLE todo_shares (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             todo_id BIGINT NOT NULL,
                             user_id BIGINT NOT NULL,

                             shared_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_todo_shares_todo
                                 FOREIGN KEY (todo_id)
                                     REFERENCES todos(id),

                             CONSTRAINT fk_todo_shares_user
                                 FOREIGN KEY (user_id)
                                     REFERENCES users(id),

                             CONSTRAINT uk_todo_shares_todo_user
                                 UNIQUE (todo_id, user_id)
);